name: Weld-JUnit CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build-weld-junit:
    name: "Weld-JUnit build, JDK ${{matrix.java.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - { name: "8",
              java-version: 8,
          }
          - {
            name: "11",
            java-version: 11,
          }
          - {
            name: "12",
            java-version: 12,
          }
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK @{}
      uses: actions/setup-java@v1.4.3
      with:
        java-version: ${{ matrix.java.java-version }}
    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
      shell: bash
    - name: Cache Maven Repository
      id: cache-maven
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        # Caching is an automated pre/post action that installs the cache if the key exists and exports the cache
        # after the job is done. In this case we refresh the cache monthly (by changing key) to avoid unlimited growth.
        key: q2maven-master-${{ steps.get-date.outputs.date }}
    - name: Build with Maven
      run: WELD_JUNIT_DEBUG=spotbugs mvn clean install -Dspotbugs.failOnError=true
    - name: Delete Local Artifacts From Cache
      shell: bash
      run: rm -r ~/.m2/repository/org/jboss/weld/weld-junit*
    - name: Prepare failure archive (if maven failed)
      if: failure()
      shell: bash
      run: find . -name '*-reports' -type d | tar -czf test-reports.tgz -T -
    - name: Upload failure Archive (if maven failed)
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: test-reports-jdk${{matrix.java.name}}
        path: 'test-reports.tgz'
